OMEGA_APIKEY: 6d077fd472decc8bb688dbbfebfebdb995e88404
OMEGA_CELERY_CONFIG:
  BROKER_URL: amqp://hub.omegaml.io:5672//
  CELERY_ACCEPT_CONTENT:
  - pickle
  - json
  CELERY_RESULT_BACKEND: amqp
  CELERY_TASK_SERIALIZER: pickle
OMEGA_MONGO_COLLECTION: omegaml
OMEGA_MONGO_URL: mongodb://ADMM4WR4YscUvbYfxDHsnJA7GzpqftS2493N:UpMMxfWP3ZarHddPCkWUP25KJawRCGbjCkMX@hub.omegaml.io:27017/FD3uZGeL327KWmhXJ4fdA2v4gPdeEJSVwCHD
OMEGA_NOTEBOOK_COLLECTION: ipynb
OMEGA_TMP: /tmp
OMEGA_USERID: user14
