version: '3'
services:
  omegaml-dev:
    image: omegaml/omegaml-dev
    working_dir: /omegaml
    volumes:
      - ../omegaml:/omegaml
      - ../omegaml-ce:/omegaml-ce
    environment:
      - MONGO_HOST=mongo:27017
      - BROKER_URL=amqp://rabbitmq:5672//
      - OMEGA_BROKER=amqp://rabbitmq:5672//
      - OMEGA_JYHUB_TOKEN=b7b034f57d442e605ab91f88a8936149e968e12e
      - C_FORCE_ROOT=true
    depends_on:
      - mongo
    command: tail -f /dev/null
    ports:
      - "8000:8000"
      - "5000:5000"
      - "9222:9222"

  mongo:
    image: mongo:3.6.8-stretch
    ports:
      - "27017:27017"
      - "28017:28017"
    command: ["--auth", "--oplogSize", "100"]

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
