version: '3'
services:
  mongo:
    image: mongo:3.6.8-stretch
    ports:
      - "27017:27017"
      - "28017:28017"
    command: ["--auth", "--oplogSize", "100"]
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
