version: '3'
services:
  omegaml-dev:
    image: omegaml/omegaml-dev
    working_dir: /omegaml
    volumes:
      - ../omegaml:/omegaml
      - ../omegaml-ce:/omegaml-ce
      - ..:/external
    environment:
      - MONGO_HOST=mongodb:27017
      - MONGO_ADMIN_URL=mongodb://admin:jk3XVEpbpevN4BgtEbmcCpVM24gc7RVB@mongodb/admin
      - OMEGA_MONGO_URL=mongodb://admin:jk3XVEpbpevN4BgtEbmcCpVM24gc7RVB@mongodb/userdb
      - BROKER_URL=amqp://rabbitmq:5671//
      - OMEGA_BROKER=amqp://omegaml:ZQQycr43FQFe9fqWqh2KBmauAGT9XdUe@rabbitmq:5671/omegaml
      - OMEGA_JYHUB_TOKEN=b7b034f57d442e605ab91f88a8936149e968e12e
      - C_FORCE_ROOT=true
      - CA_CERTS_PATH=/omegaml/release/dist/omegaml-dev/etc/mongo/certs/ca_certificate.pem
      - OMEGA_USESSL=yes
      - CELERY_Q=celery
      - DJANGO_DEBUG=1
    depends_on:
      - mongodb
      - rabbitmq
    command: tail -f /dev/null
    ports:
      - "8000:8000"
      - "5000:5000"
      - "9222:9222"
    user: ${CURRENT_USER}

  mongodb:
    image: mongo:3.6.8-stretch
    ports:
      - "27017:27017"
      - "28017:28017"
    volumes:
      - ./release/dist/omegaml-dev/etc/mongo/certs/server_key.pem:/etc/mongo/server_key.pem
    command: 
      - "--auth"
      - "--sslMode"
      - "preferSSL"
      - "--sslPEMKeyFile"
      - "etc/mongo/server_key.pem"
      - "--oplogSize"
      - "100"
  
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "5671:5671"
    hostname: rabbitmq
    volumes:
      - ./release/dist/omegaml-dev/etc/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./release/dist/omegaml-dev/etc/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./release/dist/omegaml-dev/etc/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./release/dist/omegaml-dev/etc/rabbitmq/certs:/etc/rabbitmq/certs
