version: 2
jobs:
  build:
    working_directory: /home/circleci
    machine:
      image: ubuntu-1604:201903-01
    resource_class: xlarge
    steps:
    - run:
        name: Install system packages
        command: |
          sudo apt-get -q update
          sudo apt-get -q -y install libmysqlclient-dev
    - checkout:
        path: /home/circleci/omegaml
    - run:
        name: Merge current master into PR branch
        command: |
          pr_number=${CI_PULL_REQUEST//*pull\//}
          if [ -n "$pr_number" ]
          then
            echo "Building PR #$pr_number. Try to merge current master."
            cd omegaml
            git fetch
            git checkout origin/master
            git pull --ff-only origin "refs/pull/$pr_number/head" || \
              (echo "Merge failed. Please merge manually into your branch."; exit 1)
          else
            echo "Not a PR build."
          fi
    - run:
        name: Setup local build env
        command: |
          cd omegaml
          scripts/initlocal.sh --deps --setup --noinit
          # quick fix for allowing docker user to deal with circleci-owned files
          chmod -f -R 777 ~ || true
    - run:
        name: Run unit tests
        command: |
          cd omegaml
          export CURRENT_USER=omegadev
          scripts/rundev.sh --docker --clean --cmd "make test"
        shell: /bin/bash -l -eo pipefail
    - run:
        # TODO replace with a livetest image instead of local installation
        name: Build image and run live tests
        command: |
          source ~/miniconda3/etc/profile.d/conda.sh
          conda activate base
          mkdir -p ~/.omegaml
          sudo chown -R circleci.circleci ~/.omegaml/
          echo $BEHAVE_YML | base64 -d > ~/.omegaml/behave.yml
          cd omegaml
          scripts/initlocal.sh --install --noinit
          docker login -u omegaml -p $DOCKER_PASS
          export CURRENT_USER=omegadev
          LIVETEST_BEHAVE_EXTRA_OPTS="--tags ~tfestimator --tags ~tfkeras --tags ~apphub --tags ~snowflake" make dist
        shell: /bin/bash -l -eo pipefail
    - store_artifacts:
        path: /tmp/screenshots
workflows:
  version: 2
  workflow:
    jobs:
    - build:
        context: omegaml
