version: 2
jobs:
  build:
    working_directory: /home/circleci
    machine:
      image: ubuntu-1604:201903-01
    steps:
    - run:
        name: Install system packages
        command: |
          sudo apt-get -q update
          sudo apt-get -q -y install libmysqlclient-dev texlive-xetex texlive-generic-extra
    - checkout:
        path: /home/circleci/omegaml
    - run:
        name: Merge current master into PR branch
        command: |
          pr_number=${CI_PULL_REQUEST//*pull\//}
          if [ -n "$pr_number" ]
          then
            echo "Building PR #$pr_number. Try to merge current master."
            cd omegaml
            git fetch
            git checkout origin/master
            git pull --ff-only origin "refs/pull/$pr_number/head" || \
              (echo "Merge failed. Please merge manually into your branch."; exit 1)
          else
            echo "Not a PR build."
          fi
    - run:
        name: Install Miniconda
        command: |
          curl -O --silent --show-error https://repo.anaconda.com/miniconda/Miniconda3-4.5.12-Linux-x86_64.sh
          sh Miniconda3-4.5.12-Linux-x86_64.sh -b
    - run:
        name: Run unit tests
        command: |
          source miniconda3/etc/profile.d/conda.sh
          cd omegaml
          source scripts/runtest.sh
        shell: /bin/bash -l -eo pipefail
    - run:
        name: Checkout sibling repos
        command: |
          git clone https://github.com/omegaml/omegaml omegaml-ce
          git clone --depth 1 https://7e7710a308996277fc9d448719d078f31193385a@github.com/omegaml/cloudmgr
          git clone --depth 1 https://7e7710a308996277fc9d448719d078f31193385a@github.com/miraculixx/stackable
          git clone --depth 1 https://7e7710a308996277fc9d448719d078f31193385a@github.com/miraculixx/landingpage
          git clone --depth 1 https://7e7710a308996277fc9d448719d078f31193385a@github.com/miraculixx/ccbackend
          git clone --depth 1 https://7e7710a308996277fc9d448719d078f31193385a@github.com/miraculixx/django-tastypie-swagger
          git clone --depth 1 https://7e7710a308996277fc9d448719d078f31193385a@github.com/miraculixx/tastypiex
          git clone --depth 1 https://7e7710a308996277fc9d448719d078f31193385a@github.com/omegaml/apps
          pushd omegaml-ce
          git fetch && git checkout d5bf1ec19e9cbd8049c361775b5bc87c24a9be9f
          popd
    - run:
        name: Run live tests
        command: |
          source miniconda3/etc/profile.d/conda.sh
          conda activate omenv
          mkdir -p ~/.omegaml
          sudo chown -R circleci.circleci ~/.omegaml/
          echo $BEHAVE_YML | base64 -d > ~/.omegaml/behave.yml
          cd omegaml
          docker login -u omegaml -p $DOCKER_PASS
          LIVETEST_BEHAVE_EXTRA_OPTS="--tags ~tfestimator --tags ~tfkeras --tags ~apphub --tags ~snowflake" make dist
        shell: /bin/bash -l -eo pipefail
    - store_artifacts:
        path: /tmp/screenshots
workflows:
  version: 2
  workflow:
    jobs:
    - build:
        context: omegaml
