version: 2
jobs:
  build:
    docker:
    - image: continuumio/miniconda3:4.5.12
    - image: mongo:3.6.8-stretch
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: foobar
      command:
      - --auth
      - --oplogSize
      - '100'
#    - image: rabbitmq
    steps:
    - checkout
    - run:
        name: Install system packages
        command: |
          apt-get -q update
          apt-get -q -y install make gcc libmariadb-dev-compat texlive texlive-xetex
    - restore_cache:
        key: v1-omegaml-enterprise-condaenv-{{ checksum "conda-requirements.txt" }}-{{ checksum
          "pip-requirements.txt" }}-{{ checksum "pip-requirements.extra" }}
    - run:
        name: Create Python environment
        command: |
          if [ ! -d /opt/conda/envs/omenv ]
          then
            conda create --offline -q -y -n omenv
            conda activate omenv
            conda install -q -y --file conda-requirements.txt
            pip install --ignore-installed -q -r pip-requirements.txt
            pip install --ignore-installed -q -r pip-requirements.extra
          fi
        shell: /bin/bash -l -eo pipefail
    - save_cache:
        key: v1-omegaml-enterprise-condaenv-{{ checksum "conda-requirements.txt" }}-{{ checksum
          "pip-requirements.txt" }}-{{ checksum "pip-requirements.extra" }}
        paths:
        - /opt/conda/envs/omenv
        - /root/.conda
#    - run:
#        name: Setup data
#        command: |
#          conda activate omenv
#          rm -f db.sqlite3
#          python manage.py migrate --noinput
#          python manage.py loaddata landingpage.json
#          python manage.py omsetupuser --username admin --email admin@omegaml.io --password test --admin --nodeploy
#          python manage.py omsetupuser --username jyadmin --staff --apikey b7b034f57d442e605ab91f88a8936149e968e12e
#        shell: /bin/bash -l -eo pipefail
#    - run:
#        name: Start processes
#        command: |
#          conda activate omenv
#          honcho start web notebook worker
#        shell: /bin/bash -l -eo pipefail
#        background: true
#        environment:
#          PORT: '8000'
#          C_FORCE_ROOT: true
    - run:
        name: Run unit tests
        command: |
          conda activate omenv
          make test
        shell: /bin/bash -l -eo pipefail
workflows:
  version: 2
  workflow:
    jobs:
    - build
